### ISSUE TITLE
feedback- no grade yet

### ISSUE THREAD

**Issue by timm** [shivamgulati1991/CSC510-SE-group-i#6]
Strengths:
- Nicely done.
- 74 respondents in your survey? Well done.
- Good use of graphics.
- Finished before deadline! 

Not-so-strong points:
- References should be inline with the names of the people being referenced.

To make references:
- create a `myrefs.bib` file.
- add `\bibliographystyle{plain} \bibliography{myrefs} \end{document}` to the _end_ of your file.
- Place some bibtex entries in your `myrefs.bib` file.
  - Pro tip: If you got to many on-line bibliography servers, there is often a "bibtext" button; e.g
    right-hand-side, yellow box, see "export formats" with "bibtex" underneath

![image](https://cloud.githubusercontent.com/assets/29195/12721290/1499f4ee-c8cd-11e5-9506-6f0a52814631.png)

Bibtext entries have labels. For example, the following entry has the label `mh:icse:09`.

```
@inproceedings{mh:icse:09,
  author    = {Emerson R. Murphy{-}Hill and
               Chris Parnin and
               Andrew P. Black},
  title     = {How we refactor, and how we know it},
  booktitle = {31st International Conference on Software Engineering, {ICSE} 2009,
               May 16-24, 2009, Vancouver, Canada, Proceedings},
  pages     = {287--297},
  year      = {2009}, 
  url       = {http://dx.doi.org/10.1109/ICSE.2009.5070529},
  doi       = {10.1109/ICSE.2009.5070529}, 
}
```

To insert this into the article somewhere in the body text, use `\cite{mh:icse:09}`.

**Comment by priysha** [comment]
Mentioned changed made in the report.
